<script setup lang="ts">
import type { AppRole } from '~/types/ui'
import { getNavigation, getRoleLabel } from '~/utils/navigation'
const p=defineProps<{role:AppRole}>();const route=useRoute();const open=ref(false);const nav=computed(()=>getNavigation(p.role));const label=computed(()=>getRoleLabel(p.role));
const people={admin:{name:'Raiven Supan',sub:'System administrator',initials:'RS'},instructor:{name:'Prof. Raiven Supan',sub:'IT Instructor',initials:'RS'},student:{name:'Angela Cruz',sub:'BSIT 2A',initials:'AC'}};const person=computed(()=>people[p.role]);
const active=(path:string)=>route.path===path||(path!==`/${p.role}/dashboard`&&route.path.startsWith(path+'/'));
watch(()=>route.fullPath,()=>open.value=false)
</script>
<template><div class="min-h-screen bg-muted/30"><div v-if="open" class="fixed inset-0 z-40 bg-slate-950/45 backdrop-blur-sm lg:hidden" @click="open=false"/><aside class="fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-white/10 bg-slate-950 text-white transition-transform lg:translate-x-0" :class="open?'translate-x-0':'-translate-x-full'"><div class="border-b border-white/10 px-5 py-5"><BrandMark inverse /></div><div class="px-4 pt-5"><div class="rounded-2xl border border-white/10 bg-white/5 p-3"><div class="flex items-center gap-3"><UAvatar :text="person.initials"/><div class="min-w-0"><p class="truncate text-sm font-bold">{{person.name}}</p><p class="truncate text-xs text-slate-400">{{person.sub}}</p></div></div></div></div><nav class="flex-1 overflow-y-auto px-4 py-5"><p class="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.22em] text-slate-500">{{label}}</p><NuxtLink v-for="item in nav" :key="item.to" :to="item.to" class="mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition" :class="active(item.to)?'bg-brand-600 text-white':'text-slate-300 hover:bg-white/10 hover:text-white'"><UIcon :name="item.icon" class="size-5"/>{{item.label}}</NuxtLink></nav><div class="border-t border-white/10 p-4"><NuxtLink to="/" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-300 hover:bg-white/10"><UIcon name="i-lucide-log-out" class="size-5"/>Sign out</NuxtLink></div></aside><div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 border-b border-default bg-default/90 backdrop-blur-xl"><div class="flex h-17 items-center gap-3 px-4 sm:px-6 lg:px-8"><UButton color="neutral" variant="ghost" icon="i-lucide-menu" class="lg:hidden" @click="open=true"/><div class="hidden flex-1 md:block"><div class="relative max-w-lg"><UIcon name="i-lucide-search" class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><input class="h-10 w-full rounded-xl border border-default bg-elevated/60 pl-10 pr-4 text-sm outline-none focus:border-primary" placeholder="Search classes, assessments, or students"></div></div><div class="ml-auto flex items-center gap-2"><UColorModeButton/><UButton color="neutral" variant="ghost" icon="i-lucide-bell"/><UAvatar :text="person.initials" size="sm"/></div></div></header><main class="px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><slot /></main></div></div></template>
